repos:
  # will use shellcheck to check shell script files and check-yaml to validate docker-compose
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check