version: '3.8'

volumes:
  db_data:
  pgadmin:

networks:
  appNetwork:
    driver: bridge
  
services:

  # https://hub.docker.com/_/postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB:        ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appNetwork

  # https://hub.docker.com/r/dpage/pgadmin4/
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_PORT:             ${PGADMIN_PORT}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - appNetwork

  # https://hub.docker.com/r/postgrest/postgrest/
  # https://postgrest.org/en/stable/install.html#docker
  pgrest:
    container_name: pgrest
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI:                   postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA:                public
      PGRST_DB_ANON_ROLE:             ${POSTGRES_USER} #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:${PGREST_PORT}
    ports:
      - "${PGREST_PORT}:${PGREST_PORT}"
    depends_on:
      - postgres
    networks:
      - appNetwork

  # https://hub.docker.com/r/swaggerapi/swagger-ui
  pgrest-swagger:
    container_name: pgrest-swagger
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      API_URL: http://localhost:${PGREST_PORT}/
    ports:
      - "8080:8080"
    depends_on:
      - pgrest
    networks:
      - appNetwork
